### ISSUE TITLE
context_package()

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/ask#42]
we have context_repo() for the package in development but I'd like to be able to ask questions about another package.

There are several components : 
* the help files
* the vignettes
* the code
* whether to include the source in the code (if installed with source)
* special files like DESCRIPTION, NAMESPACE, LICENSE
It's better to have 

I think having only the doc in the context by default is reasonable because many package will be too big to the context window threshold.

This would allow us to ask precise questions about a package and the way it works. e.g. we suspect a package has an unexported helper that might help, or simpler: the default llm suggestions are not good because the pkg is not (or was not) well known so the training data is not enough.

**Comment by krlmlr** [comment]
Can the new models "browse the internet" so that the context is "just" a URL, perhaps?

**Comment by moodymudskipper** [comment]
Unfortunately no, through the API you cannot make chatgpt browse the internet
